# Generated by Django 2.1.7 on 2019-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
