# Generated by Django 2.1.7 on 2019-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190322_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
