# Generated by Django 2.1.7 on 2019-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190326_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='super_customer',
            field=models.BooleanField(default=False),
        ),
    ]
