# Generated by Django 2.1.7 on 2019-04-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_customer_super_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='super_shop',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Shops'),
            preserve_default=False,
        ),
    ]
