# Generated by Django 2.1.7 on 2019-04-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_customer_super_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='super_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Shops'),
        ),
    ]
