# Generated by Django 2.1.7 on 2019-04-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190420_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='super_staffedit',
            field=models.BooleanField(default=False),
        ),
    ]
