# Generated by Django 2.1.7 on 2019-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_customer_super_staffedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='super_was',
            field=models.BooleanField(default=False),
        ),
    ]
