# Generated by Django 2.1.7 on 2019-05-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(help_text='Описание'),
        ),
    ]
