# Generated by Django 2.1.7 on 2019-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20190502_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(help_text='Зажмите Ctrl для выбора нескольких', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(),
        ),
    ]
