# Generated by Django 2.1.7 on 2019-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20190505_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='test',
            field=models.TextField(default='-'),
        ),
    ]
