# Generated by Django 2.1.7 on 2019-05-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_game_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='test',
        ),
    ]
