# Generated by Django 2.1.7 on 2019-05-06 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_game_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_create',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
