# Generated by Django 2.1.7 on 2019-05-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_game_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_create',
        ),
    ]
