# Generated by Django 2.1.7 on 2019-05-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_game_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_create',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
