# Generated by Django 2.1.7 on 2019-05-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20190506_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='date_create',
        ),
    ]
