# Generated by Django 2.1.7 on 2019-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_game_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
