# Generated by Django 2.1.7 on 2019-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20190506_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='by_create',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
