# Generated by Django 2.1.7 on 2019-05-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='user_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
