# Generated by Django 2.1.7 on 2019-05-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_check_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=333),
        ),
        migrations.AlterField(
            model_name='check',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Стоимость заказа посчитается автоматически, но вы можете вести сами', max_digits=10),
        ),
    ]
