# Generated by Django 2.1.7 on 2019-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20190507_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
