# Generated by Django 2.1.7 on 2019-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20190507_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='address',
            field=models.CharField(blank=True, default='-', help_text='Адрес покупателя, необязательно', max_length=333),
        ),
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(blank=True, help_text='ФИО покупателя, необязательно', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(default='Не оплачен', max_length=200),
        ),
        migrations.AlterField(
            model_name='check',
            name='user_id',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
