# Generated by Django 2.1.7 on 2019-05-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20190507_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='date_create',
        ),
        migrations.AlterField(
            model_name='check',
            name='name',
            field=models.CharField(blank=True, default='-', help_text='ФИО покупателя, необязательно', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(blank=True, default='Не оплачен', max_length=200, null=True),
        ),
    ]
