# Generated by Django 2.1.7 on 2019-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_auto_20190508_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
