# Generated by Django 2.1.7 on 2019-05-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_check_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='mail',
            field=models.CharField(blank=True, default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author'),
        ),
        migrations.AlterField(
            model_name='game',
            name='by_create',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Зажмите Ctrl для выбора нескольких', null=True, to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
