# Generated by Django 2.1.7 on 2019-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_auto_20190510_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='mobile',
            field=models.CharField(blank=True, default='-', max_length=12, null=True),
        ),
    ]
