# Generated by Django 2.1.7 on 2019-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_check_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='competed',
            field=models.BooleanField(default=False),
        ),
    ]
