# Generated by Django 2.2 on 2019-05-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_check_completed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='-', help_text='Адрес мероприятия', max_length=333)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='-', help_text='Название мероприятия, необязательно', max_length=200, null=True)),
                ('summary', models.CharField(blank=True, default='-', help_text='Описание мероприятия, необязательно', max_length=1000, null=True)),
            ],
        ),
    ]
