# Generated by Django 2.2 on 2019-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_gathering'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_vk', models.CharField(blank=True, max_length=255, null=True)),
                ('link_fb', models.CharField(blank=True, max_length=255, null=True)),
                ('link_tw', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
