# Generated by Django 2.2 on 2019-05-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_infosite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoSite',
        ),
    ]
