# Generated by Django 2.2 on 2019-05-21 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0051_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='leaders',
            field=models.ManyToManyField(blank=True, help_text='Зажмите Ctrl для выбора нескольких', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
