# Generated by Django 2.2 on 2019-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_meet_leaders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='leaders',
            new_name='users',
        ),
        migrations.AddField(
            model_name='meet',
            name='games',
            field=models.ManyToManyField(blank=True, help_text='Зажмите Ctrl для выбора нескольких', null=True, to='catalog.Game'),
        ),
    ]
