# Generated by Django 2.2 on 2019-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_auto_20190521_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
