# Generated by Django 2.2 on 2019-05-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20190521_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='address',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
