# Generated by Django 2.2 on 2019-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_meet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='super_shop',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Логин покупателя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='super_aboutedit',
            field=models.BooleanField(default=False, verbose_name="Редактирование 'мы'"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='super_customer',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='super_edititems',
            field=models.BooleanField(default=False, verbose_name='Редактирование товаров'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='super_staffedit',
            field=models.BooleanField(default=False, verbose_name='Редактирование сотрудников'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='super_was',
            field=models.BooleanField(default=False, verbose_name='Был сотрудником'),
        ),
    ]
