# Generated by Django 2.2 on 2019-05-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0059_meet_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='lead',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Customer'),
        ),
    ]
