# Generated by Django 2.2 on 2019-05-29 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_auto_20190530_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
