# Generated by Django 2.1 on 2019-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_meet_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название разработчика'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Это может быть карточная игра, варгейм и т.п.', max_length=200, verbose_name='Название жанра'),
        ),
    ]
